### ISSUE TITLE
temperature-lcd uses incorrect lcd library - should be upm-lcd

### ISSUE THREAD

**Issue by skiselev** [intel-iot-devkit/iot-devkit-samples#67]
temperature-lcd uses incorrect lcd library.
The upm-i2clcd library has been renamed to upm-lcd
Please update the json file with the correct library name

**Comment by Propanu** [comment]
The linker flag was left for out of box backwards compatibility with older UPM versions, when the `jhd1313m1` class was still part of it. Renaming the library doesn't break the samples, because nowadays `lupm-lcd` only contains classes for a couple of I2C based SSDxxxx displays, and these are not used by the samples.

On the other hand, I wouldn't be opposed to removing the `lupm-i2clcd` flag from the samples entirely, to "encourage" users into updating to a more recent UPM version. Our currently supported kits ship with a new enough version of MRAA & UPM already.

**Comment by anjgola** [comment]
fixed
